# Generated by Django 4.2.30 on 2026-05-07 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.product'),
        ),
    ]
