# Generated by Django 4.2.30 on 2026-05-07 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_auto_20260507_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.product'),
        ),
    ]
