# Generated by Django 4.2.30 on 2026-05-07 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0007_alter_groceryitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groceryitem',
            name='name',
        ),
    ]
