# Generated by Django 4.2.30 on 2026-05-08 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0008_remove_groceryitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
