# Generated by Django 4.2.30 on 2026-05-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0009_groceryitem_date_added_product_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='store',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='store',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
