# Generated by Django 4.2.30 on 2026-05-13 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0011_recipe_groceryitem_quantity_groceryitem_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
