# Generated by Django 4.2.30 on 2026-05-13 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0012_groceryitem_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocerylist',
            name='is_recipe_lis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='grocery_list',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocery.grocerylist'),
        ),
    ]
