# Generated by Django 4.2.30 on 2026-05-13 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0013_grocerylist_is_recipe_lis_recipe_grocery_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grocerylist',
            old_name='is_recipe_lis',
            new_name='is_recipe_list',
        ),
    ]
