# Generated by Django 6.0.5 on 2026-05-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0014_rename_is_recipe_lis_grocerylist_is_recipe_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='remaining_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
